### ISSUE TITLE
how to build Nougat for nexus 5

### ISSUE THREAD

**Issue by splinuxarm** [Unlegacy-Android/android_device_lge_hammerhead#2]
can you tell me how to build Nougat for nexus 5

**Comment by splinuxarm** [comment]
> can you tell me how to build Nougat for nexus 5

1.repo init -u git://github.com/Unlegacy-Android/android.git -b aosp-7.0
2.repo sync
3.. buile/env.sh
4.lunch hammerhead
5.make
is this right?

**Comment by airend** [comment]
You want to sync the `aosp-7.1` branch. After that, read https://source.android.com/setup/build/building#initialize.
